name: CI

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  info-block:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest          # x64
          - ubuntu-24.04       
          - ubuntu-22.04       
          - ubuntu-22.04-arm       # arm64
          - ubuntu-24.04-arm       
          - macos-14               
          - macos-26
          - macos-latest           
          - windows-latest         # x64
          - windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run info-block action
        id: info-block
        uses: ./

      - name: Run this Step only if memory_gb > 8 GB
        if: ${{ steps.info-block.outputs.memory_gb > 8 }}
        run: |
          echo "memory_gb from action: ${{ steps.info-block.outputs.memory_gb }}"
          echo "total memory is more than 8 gb"

      - name: Skip if cpu_cores < 6
        if: ${{ steps.info-block.outputs.cpu_cores > 6 }}
        run: echo "CPU cores (${{ steps.info-block.outputs.cpu_cores }}) more than 6 !"

      - name: Print all outputs
        run: |
          echo "memory_gb=${{ steps.info-block.outputs.memory_gb }}"
          echo "cpu_cores=${{ steps.info-block.outputs.cpu_cores }}"

      - name: Run info-block action (fail_on_error)
        uses: ./
        with:
          fail_on_error: true
